all:
  kfold: 1
  n_epochs: 150
  batch_size: 64
  lr_1: 0.001
  lr_2: 0.001
  w_alpha_1: 1
  w_alpha_2: 1
  top_k_cost: 10
  threshold: 0.5
  randomise_mode: 'randomised' # '' or 'randomised' or 'true_randomised'
  label_mode: 'weighted' # '' or 'weighted' or 'full'

wandb:
  mode: disabled
  project: Saigolab 2
  group: current_run
  name: current_run

baseline:
  metric_list_1: ['acc', 'roc_macro', 'roc_micro', 'roc_weighted', 'prc_macro', 'prc_micro', 'prc_weighted']
  metric_list_2: ['roc_classes', 'prc_classes']
  metric_list_3: ['top_k_cost_2']
  losses_list: ['loss2', 'loss2_1', 'loss2_2']

concat:
  metric_list_1: ['acc', 'roc_macro', 'roc_micro', 'roc_weighted', 'prc_macro', 'prc_micro', 'prc_weighted']
  metric_list_2: ['roc_classes', 'prc_classes']
  metric_list_3: ['top_k_cost_1', 'top_k_cost_2']
  losses_list: ['loss1', 'loss2', 'loss1_1', 'loss1_2', 'loss2_1', 'loss2_2']

w_se_embeds:
  metric_list_1: ['acc', 'roc_macro', 'roc_micro', 'roc_weighted', 'prc_macro', 'prc_micro', 'prc_weighted']
  metric_list_2: ['roc_classes', 'prc_classes']
  metric_list_3: ['top_k_cost_2']
  losses_list: ['loss1', 'loss2', 'loss1_1', 'loss1_2', 'loss2_1', 'loss2_2']